// <auto-generated />
#pragma warning disable
namespace Shintio.Unity
{
	public static class Scenes
	{
		public static readonly SceneInfo SampleScene = new SceneInfo(0, "SampleScene", true);
		public static readonly SceneInfo[] All = { SampleScene };
		public class SceneInfo
		{
			public readonly int Id;
			public readonly string Name;
			public readonly bool Enabled;
			
			public SceneInfo(int id, string name, bool enabled)
			{
				Id = id;
				Name = name;
				Enabled = enabled;
			}
		}
	}
}
