// <auto-generated />
#pragma warning disable
namespace Shintio.Unity
{
	public static class Tags
	{
		public const string Untagged = "Untagged";
		public const string Respawn = "Respawn";
		public const string Finish = "Finish";
		public const string EditorOnly = "EditorOnly";
		public const string MainCamera = "MainCamera";
		public const string Player = "Player";
		public const string GameController = "GameController";
	}
	public static class Layers
	{
		public const int Default = 0;
		public const int TransparentFX = 1;
		public const int Ignore_Raycast = 2;
		public const int Water = 4;
		public const int UI = 5;
	}
}
